name: my_headspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State managment 
  provider: ^6.1.5+1

  # Service Locator
  get_it: ^8.3.0 

  # Ui Optimization 
  flutter_screenutil: ^5.9.3

  # Routing
  auto_route: ^10.2.3

  # Hooks
  flutter_hooks: 0.21.3

  date_field: ^6.0.3
  flutter_svg: ^2.2.3
  intl: ^0.20.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.2.6
  lean_builder: ^0.1.3
  build_runner: ^2.10.4

flutter_gen:
  # Optional
  integrations:
    image: true
    flutter_svg: true

  colors:
    inputs:
      - assets/app_colors.xml

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/Montserrat_V.ttf


